### ISSUE TITLE
Don't `xfail` if users specify `--manual`

### ISSUE THREAD

**Issue by thejcannon** [RonnyPfannschmidt/pytest-manual-marker#7]
Right now, the tests are either deselected or `xfail`d. There's no obvious way for developers to run the tests AND expect that their tests to pass. They can run with `--runxfail`, however the `xfail` seems like an implementation detail, since it isn't documented or in _any_ of the reporting.

I propose that `--manual` has the semantics of `--runxfail` in that failing tests are reported as such.

**Comment by RonnyPfannschmidt** [comment]
the semantics of manual tests is not "failed" but "cant run automated"

until there are tills for manual assist tests (where users are expectedto step in nad act, xfail is the only sensible outcome for me
im happy to change my stance if there is a more complete description of the use-case you want to match with your request

**Comment by thejcannon** [comment]
> the semantics of manual tests is not "failed" but "cant run automated"

Sure, but I'm explicitly passing `--manual`, therefore I want to run the tests. Using [pytest.xfail](https://github.com/RonnyPfannschmidt/pytest-manual-marker/blob/647516b5b935d7626b2dc68949f78bf13fc7f33e/src/pytest_manual_marker/__init__.py#L26) won't actually run the test

> Note that no other code is executed after the [pytest.xfail()](https://docs.pytest.org/en/6.2.x/reference.html#pytest.xfail) call, differently from the marker. That’s because it is implemented internally by raising a known exception. 

So, I'm not sure how someone is supposed to run the manual test (non-automated)

**Comment by RonnyPfannschmidt** [comment]
@thejcannon manual marked tests are tests that cannot run in automation - the way the plugin is intended to use is to document testcases that require manual testing as part of test reports

there is a plan to add a manual-assist feature which would be for marking tets, which can be run but require human interaction, 
currently i dont have the bandwith to make that feature
